import "dotenv/config";
import { MongoClient } from "mongodb";

const NEW_SLANGS = [
  { term: "boh lui", dialect: "hokkien", normalized_form: "no money", confidence: 0.95, source: ["web-scrape-2026"] },
  { term: "bo lui", dialect: "hokkien", normalized_form: "no money", confidence: 0.95, source: ["web-scrape-2026"] },
  { term: "lui", dialect: "hokkien", normalized_form: "money", confidence: 0.95, source: ["web-scrape-2026"] },
  { term: "chin lui", dialect: "hokkien", normalized_form: "a lot of money", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "chia lui", dialect: "hokkien", normalized_form: "earn money", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "tiok lui", dialect: "hokkien", normalized_form: "receive money", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "khoo lui", dialect: "hokkien", normalized_form: "save money", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "sng lui", dialect: "hokkien", normalized_form: "count money", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "jit tang", dialect: "hokkien", normalized_form: "hospital", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ji tang", dialect: "hokkien", normalized_form: "hospital", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "lao kiao", dialect: "hokkien", normalized_form: "experienced elder or old hand", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "lao kiu", dialect: "hokkien", normalized_form: "experienced elder", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "lao lang", dialect: "hokkien", normalized_form: "old person", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "lao peh", dialect: "hokkien", normalized_form: "old father or elder", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "lao beh", dialect: "hokkien", normalized_form: "old father", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "lao bu", dialect: "hokkien", normalized_form: "old mother", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "lao niao", dialect: "hokkien", normalized_form: "old and frail", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "pua kang", dialect: "hokkien", normalized_form: "half disabled or broken down", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "ka ki", dialect: "hokkien", normalized_form: "yourself or oneself", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "ka ki lang", dialect: "hokkien", normalized_form: "own people or family", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "boh eng", dialect: "hokkien", normalized_form: "no time or too busy", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "bo eng", dialect: "hokkien", normalized_form: "no time or too busy", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "boh tak chek", dialect: "hokkien", normalized_form: "uneducated or illiterate", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "bo tak chek", dialect: "hokkien", normalized_form: "uneducated", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "pok kai", dialect: "cantonese", normalized_form: "bankrupt or broke", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sek bao", dialect: "hokkien", normalized_form: "eaten and full or satisfied", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "boh huat", dialect: "hokkien", normalized_form: "no way or nothing can be done", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "bo huat", dialect: "hokkien", normalized_form: "no way", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "tng", dialect: "hokkien", normalized_form: "hospital ward", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "kia", dialect: "hokkien", normalized_form: "child or person", confidence: 0.80, source: ["web-scrape-2026"] },
  { term: "ah kong", dialect: "hokkien", normalized_form: "grandfather or old man", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ah ma", dialect: "hokkien", normalized_form: "grandmother or old woman", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ah gong", dialect: "hokkien", normalized_form: "grandfather", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ah pek", dialect: "hokkien", normalized_form: "old uncle or elderly man", confidence: 0.95, source: ["web-scrape-2026"] },
  { term: "ah soh", dialect: "hokkien", normalized_form: "auntie or middle-aged woman", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ah lian", dialect: "hokkien", normalized_form: "older Chinese woman", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "nia", dialect: "hokkien", normalized_form: "only or just", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "boh nia", dialect: "hokkien", normalized_form: "only this much", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "boh kia si", dialect: "hokkien", normalized_form: "not afraid to die or fearless", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "buay sai", dialect: "hokkien", normalized_form: "cannot or not allowed", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "eh sai", dialect: "hokkien", normalized_form: "can or allowed", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "boh kang", dialect: "hokkien", normalized_form: "no work or unemployed", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "kang tau", dialect: "hokkien", normalized_form: "job opportunity or connection", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "siao", dialect: "hokkien", normalized_form: "crazy", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "siao liao", dialect: "hokkien", normalized_form: "in big trouble now", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "tio siao", dialect: "hokkien", normalized_form: "gone crazy", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "boh tak", dialect: "hokkien", normalized_form: "cannot win or no fighting chance", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "pai seh", dialect: "hokkien", normalized_form: "embarrassed or sorry", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "nang kia", dialect: "teochew", normalized_form: "person or individual", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "gao lang", dialect: "teochew", normalized_form: "old person", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "gao nang", dialect: "teochew", normalized_form: "old person", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "ao lui", dialect: "teochew", normalized_form: "have money", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "boh ao lui", dialect: "teochew", normalized_form: "have no money", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "chiak kway", dialect: "teochew", normalized_form: "eat kueh or have something good", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "teochew lang", dialect: "teochew", normalized_form: "Teochew person", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "mm sek", dialect: "cantonese", normalized_form: "do not know", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "gau sik", dialect: "cantonese", normalized_form: "experienced or knowledgeable", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "mo lui", dialect: "cantonese", normalized_form: "no money", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "yau lui", dialect: "cantonese", normalized_form: "have money or rich", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "kau dim", dialect: "cantonese", normalized_form: "settled or done", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "sei lor", dialect: "cantonese", normalized_form: "finished or doomed", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "leng lui", dialect: "cantonese", normalized_form: "pretty girl", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "leng zai", dialect: "cantonese", normalized_form: "handsome man", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "yeh yeh", dialect: "cantonese", normalized_form: "paternal grandfather", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "poh poh", dialect: "cantonese", normalized_form: "maternal grandmother", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "gong gong", dialect: "cantonese", normalized_form: "maternal grandfather", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "lo ye", dialect: "hakka", normalized_form: "old man or grandfather", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "lo po", dialect: "hakka", normalized_form: "wife", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "ciak fan", dialect: "hakka", normalized_form: "eat rice or have a meal", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "umur", dialect: "malay", normalized_form: "age", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sakit", dialect: "malay", normalized_form: "sick or pain", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sakit hati", dialect: "malay", normalized_form: "heartache or emotionally hurt", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sakit perut", dialect: "malay", normalized_form: "stomach ache", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ubat", dialect: "malay", normalized_form: "medicine", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "doktor", dialect: "malay", normalized_form: "doctor", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "klinik", dialect: "malay", normalized_form: "clinic", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "wang pencen", dialect: "malay", normalized_form: "pension money", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "pencen", dialect: "malay", normalized_form: "pension or retirement", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "orang tua", dialect: "malay", normalized_form: "old person or elder", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sudah tua", dialect: "malay", normalized_form: "already old", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "dah tua", dialect: "malay", normalized_form: "already old", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "rumah", dialect: "malay", normalized_form: "house or home", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sewa rumah", dialect: "malay", normalized_form: "rent a house", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "beli rumah", dialect: "malay", normalized_form: "buy a house", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "hutang", dialect: "malay", normalized_form: "debt", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "belanja", dialect: "malay", normalized_form: "spend money or treat someone", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "rezeki", dialect: "malay", normalized_form: "blessing or income from God", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "cukup", dialect: "malay", normalized_form: "enough or sufficient", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "tak cukup", dialect: "malay", normalized_form: "not enough", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "dah bayar", dialect: "malay", normalized_form: "already paid", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "belum bayar", dialect: "malay", normalized_form: "not yet paid", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "hari tua", dialect: "malay", normalized_form: "old age", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "masa tua", dialect: "malay", normalized_form: "old age period", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "ambil duit", dialect: "malay", normalized_form: "withdraw money", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "jimat", dialect: "malay", normalized_form: "save money or be frugal", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "tabung", dialect: "malay", normalized_form: "savings fund or piggy bank", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "vayasu", dialect: "tamil", normalized_form: "age", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "noi", dialect: "tamil", normalized_form: "illness or disease", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "vali", dialect: "tamil", normalized_form: "pain", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "marunthu", dialect: "tamil", normalized_form: "medicine", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "maruthuvamanai", dialect: "tamil", normalized_form: "hospital", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "doctor kitta po", dialect: "tamil", normalized_form: "go to the doctor", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "vitthu", dialect: "tamil", normalized_form: "house or home", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "kaasu", dialect: "tamil", normalized_form: "money or cash", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "kaasu illai", dialect: "tamil", normalized_form: "no money", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "kaasu irukka", dialect: "tamil", normalized_form: "is there money or do you have money", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "seyithi", dialect: "tamil", normalized_form: "news or information", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "velai", dialect: "tamil", normalized_form: "work or job", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "velai illai", dialect: "tamil", normalized_form: "no work or unemployed", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "sixty-five money", dialect: "singlish", normalized_form: "CPF payout at age 65", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "lock up money", dialect: "singlish", normalized_form: "CPF savings locked in", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "government keep money", dialect: "singlish", normalized_form: "CPF savings held by government", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "five-five money", dialect: "singlish", normalized_form: "CPF withdrawal at age 55", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "monthly give money", dialect: "singlish", normalized_form: "CPF LIFE monthly payout", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "every month money", dialect: "singlish", normalized_form: "CPF LIFE monthly payout", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "flat money cpf", dialect: "singlish", normalized_form: "CPF used for HDB flat purchase", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "old age money", dialect: "singlish", normalized_form: "CPF retirement savings", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "hospital money", dialect: "singlish", normalized_form: "MediSave balance", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "sick money", dialect: "singlish", normalized_form: "MediSave for medical expenses", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "medisave enough or not", dialect: "singlish", normalized_form: "is my MediSave sufficient", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "cpf cannot touch", dialect: "singlish", normalized_form: "CPF savings not yet accessible", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "minimum sum", dialect: "singlish", normalized_form: "CPF minimum retirement sum", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "top up ma", dialect: "singlish", normalized_form: "make a voluntary CPF top-up", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "tax relief cpf", dialect: "singlish", normalized_form: "CPF top-up tax relief", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "use medisave pay", dialect: "singlish", normalized_form: "pay with MediSave", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "oa interest", dialect: "singlish", normalized_form: "CPF Ordinary Account interest rate", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "extra interest", dialect: "singlish", normalized_form: "CPF extra interest for older members", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "bonus interest", dialect: "singlish", normalized_form: "CPF additional interest for first thirty thousand", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "cpf life standard", dialect: "singlish", normalized_form: "CPF LIFE Standard Plan", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "cpf life basic", dialect: "singlish", normalized_form: "CPF LIFE Basic Plan", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "escalating plan", dialect: "singlish", normalized_form: "CPF LIFE Escalating Plan", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "defer cpf", dialect: "singlish", normalized_form: "defer CPF LIFE payout start", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "start payout later", dialect: "singlish", normalized_form: "defer CPF LIFE payout", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "medifund", dialect: "singlish", normalized_form: "MediFund safety-net scheme", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "comcare", dialect: "singlish", normalized_form: "ComCare social assistance scheme", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "pioneer generation", dialect: "singlish", normalized_form: "Pioneer Generation Package benefits", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "pg card", dialect: "singlish", normalized_form: "Pioneer Generation card", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "merdeka generation", dialect: "singlish", normalized_form: "Merdeka Generation Package benefits", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "mg card", dialect: "singlish", normalized_form: "Merdeka Generation card", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "cdac", dialect: "singlish", normalized_form: "Chinese Development Assistance Council fund", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "sinda", dialect: "singlish", normalized_form: "Singapore Indian Development Association fund", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "mendaki", dialect: "singlish", normalized_form: "Yayasan MENDAKI Malay community fund", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "gst voucher", dialect: "singlish", normalized_form: "GST Voucher cash payout", confidence: 0.90, source: ["web-scrape-2026"] },
  { term: "passion card", dialect: "singlish", normalized_form: "PAssion Card senior benefits card", confidence: 0.85, source: ["web-scrape-2026"] },
  { term: "ntuc card", dialect: "singlish", normalized_form: "NTUC union membership card", confidence: 0.85, source: ["web-scrape-2026"] },
];

async function main() {
  const client = new MongoClient(process.env.MONGODB_URI!, { serverSelectionTimeoutMS: 10000 });
  try {
    await client.connect();
    const col = client.db("pulse").collection("slang_dictionary");
    let inserted = 0, skipped = 0;
    for (const entry of NEW_SLANGS) {
      const res = await col.updateOne(
        { term: entry.term },
        { $setOnInsert: entry },
        { upsert: true },
      );
      if (res.upsertedCount > 0) inserted++;
      else skipped++;
    }
    const total = await col.countDocuments();
    console.log(`Done — inserted: ${inserted}, skipped (already existed): ${skipped}, total: ${total}`);
  } finally {
    await client.close();
  }
}
main().catch(e => { console.error(e); process.exit(1); });
